Seção 1 atualizada de acordo com o original
PHPSP/php-the-right-way pull request #153
Opened 2021-08-09 20:09 UTC by dianaarnos

Este PR atualiza o README e a primeira seção do site de acordo com o original.
Também arante que todas as páginas atualizadas respeitem o padrão de 120 caracteres por linha definido no [Guia de Estilo](https://github.com/PHPSP/php-the-right-way#guia-de-estilo-para-o-contribuidor).

Esse é o primeiro de uma série de PRs que vão atualizar todas as seções do site: tradução, links, informacões atualizadas de acordo com o site original.

2021-08-10 14:41 UTC, nawarian requested changes
Obrigadão pelo PR, viu?

Eu deixei alguns comentários sobre linguagem neutra. A tradução parece já estar num estado bacana.

Além daqueles, eu deixei comentários sobre a utilização de crase pra mostrar snippet de código. Eu tenho a impressão de que o seu `.md` está bugado e recomendo que teste gerar as páginas e verificar aqueles snippets mais uma vez.

---
Nota para o mundo: escrever em PT-BR com neutralidade de gênero é um baita desafio

2021-08-10 14:41 UTC, nawarian commented on _includes/welcome.md
> +Há muitas informações desatualizadas na Web que levam os novos usuários de PHP a se desorientar, propagando más práticas
Pra simplificar o texto eu recomendo 1) manter "informação" no singular e 2) removes os gerúndios:

> Há muita informação desatualizada na Web que desorienta novos usuários de PHP, propaga más práticas e código inseguro.

2021-08-10 14:41 UTC, nawarian commented on _includes/welcome.md
> +_Não há uma maneira canônica de usar PHP_. Este site visa introduzir novos desenvolvedores PHP a alguns tópicos que eles
Acho que trocar `canônica` por `única` torna o texto mais fácil de digerir. Pra deixar mais natural em pt-br eu tomaria a liberdade de inverter a negação dizendo que `há várias maneiras de usar PHP`.

Também recomendo trocar `novos desenvolvedores` por `iniciantes` em favor de adotar uma linguagem neutra em gênero. Isso vai te forçar a repensar o resto da frase. Vou deixar aqui minha sugestão:

> _Há várias maneiras de usar PHP_. Este site visa introduzir iniciantes em PHP a alguns tópicos que talvez só seriam descobertos tarde demais, e pretende oferecer a profissionais experientes algumas ideias sobre tópicos que vêm sendo utilizados por anos sem questionamento. Este website [..]

2021-08-10 14:41 UTC, nawarian commented on _includes/welcome.md
> +Ajude a tornar este site o melhor recurso para novos programadores PHP! [Contribua no GitHub][2]
Recomendo trocar "novos programadores PHP" por "iniciantes em PHP" em favor de uma linguagem neutra em gênero.

2021-08-10 14:41 UTC, nawarian commented on _includes/welcome.md
> +_PHP: Do Jeito Certo_ possui banners que você pode usar em seu site. Mostre seu apoio e deixe que novos desenvolvedores
Recomendo trocar "novos desenvolvedores" por "mais iniciantes" em favor de uma linguagem neutra em gênero.

2021-08-10 14:41 UTC, nawarian commented on _posts/01-05-01-Windows-Setup.md
> +e [WAMP][wamp] irão ajudá-lo a montar rapidamente um ambiente de desenvolvimento em Windows. Dito isso, estas
`ajudá-lo` implica o gênero masculino de quem lê. Recomendo trocar por "te ajudar" em em favor de uma linguagem neutra em gênero

2021-08-10 14:41 UTC, nawarian commented on _posts/01-06-01-Common-Directory-Structure.md
> +anos, esta resposta tem sido sempre "onde está o `DocumentRoot’ (a raiz do diretório)". Embora esta resposta não seja
Não testei este snippet, mas acho que "DocumentRoot" está bugado. Talvez o símbolo "`" (crase) seja mais adequado após a palavra "DocumentRoot", em vez de "’"

2021-08-10 14:41 UTC, nawarian commented on _posts/01-06-01-Common-Directory-Structure.md
> +Por razões de segurança, os arquivos de configuração não devem ser acessíveis pelos visitantes de um site; portanto, os
Recomendo trocar "pelos visitantes" por "por visitantes" em favor de uma linguagem neutra em gênero.

2021-08-10 14:41 UTC, nawarian commented on _posts/01-06-01-Common-Directory-Structure.md
> +nesta pesquisa. Nesta estrutura de diretórios, o `DocumentRoot' deve apontar para `public/', os testes unitários devem
Não testei este snippet, mas acho que "DocumentRoot" está bugado. Talvez o símbolo "`" (crase) seja mais adequado após a palavra "DocumentRoot", em vez de "’". O mesmo se aplica a cada diretório mencionado.

2021-08-10 14:41 UTC, nawarian commented on _posts/01-06-01-Common-Directory-Structure.md
> +vendor/'. Para outros arquivos e diretórios, obedecer ao [Standard PHP Package Skeleton] fará mais sentido para os
Recomendo trocar "os contribuidores de" por "quem contribuem com" em favor de uma linguagem neutra em gênero.

2021-08-12 18:19 UTC, dianaarnos commented
Obrigada pelo review @nawarian <3 

Eu atualizei as partes que você mencionou e também revisei todos os textos desse PR com essas ideias na cabeça e adaptei mais algumas frases e corrigi mais alguns snippets.

2021-08-13 04:57 UTC, nawarian approved these changes

2021-08-15 13:00 UTC, merged