Seção 03 atualizada de acordo com original
PHPSP/php-the-right-way pull request #155
Opened 2021-08-09 20:16 UTC by dianaarnos

Este PR atualiza a seção 3 do site de acordo com o original.
Também garante que todas as páginas atualizadas respeitem o padrão de 120 caracteres por linha definido no [Guia de Estilo](https://github.com/PHPSP/php-the-right-way#guia-de-estilo-para-o-contribuidor).

Esse é o segundo de uma série de PRs que vão atualizar todas as seções do site: tradução, links, informações atualizadas de acordo com o site original.

PR para a seção 2: https://github.com/PHPSP/php-the-right-way/pull/154

2021-08-12 17:33 UTC, Morkhusz requested changes

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-02-01-Programming-Paradigms.md
>  (callables) tanto que elas podem ser usadas indistintamente com funções anónimas na maioria dos casos.
```suggestion
(callables) tanto que elas podem ser usadas indistintamente com funções anônimas na maioria dos casos.
```
sei que vc não mexeu neste trecho mas havia um **typo** rs

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-02-01-Programming-Paradigms.md
>  `method_missing`, mas ele está disponível com `__call()` e __callStatic().
```suggestion
`method_missing`, mas ele está disponível com `__call()` e `__callStatic()`.
```
Como você adicionou as crases envolvendo os demais métodos mágicos, acho que seria interessante adicionar ao **callStatic** também

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-04-01-Standard-PHP-Library.md
> +[spl]: http://php.net/book.spl
```suggestion
[spl]: https://php.net/book.spl
```
acha interessante alterar para https o link? os demais links até agora estão todos com https já
testei o link e há um redirect para https então caso não ache necessário só ignorar

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-05-01-Command-Line-Interface.md
>  número de outras [opções de linha comando][cli-options] úteis.
```suggestion
A opção `-a` fornece um shell interativo, similar ao IRB do ruby e ao shell interativo do python. Também existem várias outras [opções de linha comando][cli-options] úteis.
```
A sugestão acima é mais "sutil", apesar de você não ter mexido nesta parte do texto acredito que fica menos "robótico" com a sugestão acima.
A tradução da forma que está funciona então aceite se achar que faz sentido pra ti também

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-05-01-Command-Line-Interface.md
> +Uso: php hello.php [nome]
```suggestion
Uso: php hello.php <nome>
```
na linha **34** foi alterado o uso de `[]` para `<>` desta forma sugiro seguir o mesmo padrão aqui

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-06-01-XDebug.md
>  [xdebug-install]: http://xdebug.org/docs/install
```suggestion
[xdebug-docs]: https://xdebug.org/docs/
[xdebug-install]: https://xdebug.org/docs/install
```

2021-08-12 17:33 UTC, Morkhusz commented on _posts/03-06-01-XDebug.md
> +[macgdbp-install]: http://www.bluestatic.org/software/macgdbp/
```suggestion
[macgdbp-install]: https://www.bluestatic.org/software/macgdbp/
```

2021-08-12 18:36 UTC, dianaarnos commented on _posts/03-02-01-Programming-Paradigms.md
>  `method_missing`, mas ele está disponível com `__call()` e __callStatic().
Good catch... passou completamente despercebido hauhauahuha

2021-08-12 18:42 UTC, dianaarnos commented
Mudando pra draft enquanto reviso a questão de neutralidade de gênero

2021-08-13 05:15 UTC, nawarian requested changes
Oiê. Deixei dois pontos só, espero que não te consuma muito tempo e energia. O resto do texto pra mim tá ótimo.

Obrigadão pelo PR <3

2021-08-13 05:15 UTC, nawarian commented on _posts/03-03-01-Namespaces.md
> +Em outubro de 2014 o PHP-FIG (Framework Interop Group) depreciou o padrão para autoloading anterior: a [PSR-0][psr0].
`depreciou` não é uma tradução correta. Tu se importa de ajustar aqui também? <3

`depreciar` em pt-br significa "reduzir o preço" e normalmente é como devs traduzem `deprecate` (desaprovar).
A palavra correta aqui é `descontinuar` -> `descontinuou`.

> Em outubro de 2014 o PHP-FIG (Framework Interop Group) **_descontinuou_** o padrão [...]

2021-08-13 05:15 UTC, nawarian commented on _posts/03-06-01-XDebug.md
> +Se você perceber que você está sem conseguir sair do lugar, querendo a recorrer a *var_dump*/*print_r*, e ainda assim
"[...] querendo a recorrer a var_dump/print_r [...]"

Tem um `a` sobrando antes de "recorrer"

2021-08-15 13:11 UTC, dianaarnos commented
opa, good catch XD
Obrigada!

PR atualizado

2021-08-17 05:47 UTC, nawarian approved these changes

2021-08-17 20:16 UTC, merged