Seção 04 atualizada de acordo com original
PHPSP/php-the-right-way pull request #156
Opened 2021-08-09 20:18 UTC by dianaarnos

Este PR atualiza a seção 4 do site de acordo com o original.
Também garante que todas as páginas atualizadas respeitem o padrão de 120 caracteres por linha definido no [Guia de Estilo](https://github.com/PHPSP/php-the-right-way#guia-de-estilo-para-o-contribuidor).

Esse é o segundo de uma série de PRs que vão atualizar todas as seções do site: tradução, links, informações atualizadas de acordo com o site original.

PR para a seção 3: https://github.com/PHPSP/php-the-right-way/pull/155

2021-08-12 19:05 UTC, dianaarnos commented
Mudando pra draft enquanto reviso a questão da neutralidade de gênero

2021-08-13 05:30 UTC, nawarian requested changes
Como você comentou estar revisando os vieses de gênero eu não comentei nada sobre isso neste review.

Mais uma vez, obrigado pela iniciativa! 💚

2021-08-13 05:30 UTC, nawarian commented on _posts/04-02-01-Composer-and-Packagist.md
> +O Composer é o gerenciador de dependências recomendado para PHP. Lista as dependências de seu projeto em um arquivo `
Tem uma quebra de linha entre uma crase e a outra. Não sei se isso funciona bem com o processador de MD. Consegue confirmar pra gente?

2021-08-13 05:30 UTC, nawarian commented on _posts/04-02-01-Composer-and-Packagist.md
> +Há uma infinidade de bibliotecas PHP que são compatíveis com o Composer e estão prontas para serem usadas em seu
opcional: `que são` é redundante em "Há uma infinidade de bibliotecas PHP ~que são~ compatíveis com o Composer [...]".

2021-08-13 05:30 UTC, nawarian commented on _posts/04-02-01-Composer-and-Packagist.md
> +corrompido ou foi adulterado. O instalador instala um arquivo binário `composer.phar` no seu _diretório atual_.
"O instalador **_instala_** [...]". Ficaria melhor "gera" ou "cria", na minha opinião

2021-08-13 05:30 UTC, nawarian commented on _posts/04-02-01-Composer-and-Packagist.md
> +fazer isso, rode o próximo comando:
Eu acho que em vez de  "próximo" a palavra "seguinte" daria maior sentido a frase

2021-08-13 05:30 UTC, nawarian commented on _posts/04-02-01-Composer-and-Packagist.md
> +alterrá-lo na mão se preferir ou usar o próprio Composer. O comando `composer require` adiciona uma dependência ao
Tem um `r` a mais em `alterá-lo`

2021-08-13 05:30 UTC, nawarian commented on _posts/04-02-01-Composer-and-Packagist.md
> +arquivo `composer.lock` está incluído, pois quando eles executarem o comando `composer install` eles receberão as mesmas
"Se você compartilhar seu projeto com **_outras pessoas_**, certifique-se de que [...] pois quando **_eles_** executarem o comando [...]" 

"**_eles_**" não concorda em gênero com "**_pessoas_**".

Atenção que `eles` aparece duas vezes na mesma frase. Então se tu corrigir aqui, dê uma olhada na segunda ocorrência também

2021-08-17 05:50 UTC, nawarian approved these changes

2021-08-17 20:17 UTC, merged

2022-09-05 21:16 UTC, rdeprera commented
É sério mesmo que estão implementando neutralidade de gênero na tradução? E de um Creative Commons?
É verdade isso ou li errado @dianaarnos  ?